CREATE TABLE fpusnr_arc_log_view (
    MachineDescription NVARCHAR(50),
    DateTime DATE,
    Shift NVARCHAR(50),
    Crew NVARCHAR(50),
    SpeciesName NVARCHAR(50),
    GradeName NVARCHAR(50),
    CutPatternDescription NVARCHAR(250),
    DiameterDescription NVARCHAR(250),
    LengthDescription NVARCHAR(250),
    Solution INT,
    Bin INT,
    Sweep NVARCHAR(38),
    Taper NVARCHAR(38),
    SmallEndDiameter NVARCHAR(38),
    LargeEndDiameter NVARCHAR(38),
    ProductionValue NVARCHAR(38),
    MarketValue NVARCHAR(38),
    UserVolume NVARCHAR(38),
    AdjustedGrossVol NVARCHAR(38),
    NominalLumberVolume NVARCHAR(38),
    Length NVARCHAR(38),
    SawDustValue NVARCHAR(38),
    SawDustVolume NVARCHAR(38),
    ChipValue NVARCHAR(38),
    ChipVolume NVARCHAR(38),
    NumberOfEdgerSlabs INT,
    OptTime NVARCHAR(38),
    ChainSpeed NVARCHAR(38),
    LogGap NVARCHAR(38),
    TurnDegree NVARCHAR(38),
    LogCount INT,
    OptimizerType NVARCHAR(50),
    CantWidth NVARCHAR(50),
    NumberOfCuts INT,
    NumberOfPasses INT,
    NumberOfOverrides INT,
    NumberOfWasteCuts INT,
    NumberOfManualCuts INT,
    SolutionType NVARCHAR(16),
    FiberClass NVARCHAR(50),
    TagStartTime DATETIME2,
    UserVolume_1 NVARCHAR(255),
    PatternNumber INT,
    StationId INT,
    DroppedBoardCount INT,
    GhostBoardCount INT,
    PatternChangeCount INT,
    IsMetric INT,
    NumberOfBoards INT,
    NumberOfForceTerms INT,
    PassNumber INT,
    OverrideType NVARCHAR(16),
    Axis NVARCHAR(16),
    CutDirection NVARCHAR(16),
    DeviceName NVARCHAR(16),
    CutTime DECIMAL(18,4),
    CutLength DECIMAL(18,4),
    Kerf DECIMAL(18,4),
    DevicePosition DECIMAL(18,4),
    Curvature NVARCHAR(38),
    AChipOnly SMALLINT,
    BChipOnly SMALLINT,
    ChipOnlySolution SMALLINT,
    AAxisPasses INT,
    NumberOfTurns INT,
    AChipReductionPasses INT,
    BChipReductionPasses INT,
    HasFreq INT,
    NaturalFreq NVARCHAR(38),
    Confidence INT,
    CurveDeflection NVARCHAR(38),
    PassCount INT,
    FlareCount INT,
    Ovality NVARCHAR(38),
    EdgerFlitchCount INT,
    SubWidthBoardCount INT,
    NumberOfCants INT,
    OptTimeClass NVARCHAR(50),
    CantBoardCount INT,
    CantFinishedVolume NVARCHAR(38),
    TurnDescription NVARCHAR(50),
    DetectedTurnError NVARCHAR(38),
    CorrectedTurnError NVARCHAR(38),
    UncorrectedTurnError NVARCHAR(38),
    ClassifiedDetectedTurnError NVARCHAR(50),
    ClassifiedCorrectedTurnError NVARCHAR(50),
    ClassifiedUncorrectedTurnError NVARCHAR(50),
    NumberOfA1Cuts INT,
    NumberOfA2Cuts INT,
    NumberOfB1Cuts INT,
    NumberOfB2Cuts INT,
    AcousticVelocity NVARCHAR(38),
    VelocityClass NVARCHAR(50),
    TagNames NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    VolumeType_1 NVARCHAR(50),
    VolumeUnits_1 NVARCHAR(50),
    VolumeType_2 NVARCHAR(50),
    VolumeUnits_2 NVARCHAR(50),
    VolumeType_3 NVARCHAR(50),
    VolumeUnits_3 NVARCHAR(255),
    IDLogView INT
);

CREATE TABLE fpusnr_log_view (
    MachineDescription NVARCHAR(50),
    DateTime DATE,
    Shift NVARCHAR(50),
    Crew NVARCHAR(50),
    SpeciesName NVARCHAR(50),
    GradeName NVARCHAR(50),
    CutPatternDescription NVARCHAR(250),
    DiameterDescription NVARCHAR(250),
    LengthDescription NVARCHAR(250),
    Solution INT,
    Bin INT,
    Sweep NVARCHAR(38),
    Taper NVARCHAR(38),
    SmallEndDiameter NVARCHAR(38),
    LargeEndDiameter NVARCHAR(38),
    ProductionValue NVARCHAR(38),
    MarketValue NVARCHAR(38),
    UserVolume NVARCHAR(38),
    AdjustedGrossVol NVARCHAR(38),
    NominalLumberVolume NVARCHAR(38),
    Length NVARCHAR(38),
    SawDustValue NVARCHAR(38),
    SawDustVolume NVARCHAR(38),
    ChipValue NVARCHAR(38),
    ChipVolume NVARCHAR(38),
    NumberOfEdgerSlabs INT,
    OptTime NVARCHAR(38),
    ChainSpeed NVARCHAR(38),
    LogGap NVARCHAR(38),
    TurnDegree NVARCHAR(38),
    LogCount INT,
    OptimizerType NVARCHAR(50),
    CantWidth NVARCHAR(50),
    NumberOfCuts INT,
    NumberOfPasses INT,
    NumberOfOverrides INT,
    NumberOfWasteCuts INT,
    NumberOfManualCuts INT,
    SolutionType NVARCHAR(16),
    FiberClass NVARCHAR(50),
    TagStartTime DATETIME2,
    UserVolume_1 NVARCHAR(255),
    PatternNumber INT,
    StationId INT,
    DroppedBoardCount INT,
    GhostBoardCount INT,
    PatternChangeCount INT,
    IsMetric INT,
    NumberOfBoards INT,
    NumberOfForceTerms INT,
    PassNumber INT,
    OverrideType NVARCHAR(16),
    Axis NVARCHAR(16),
    CutDirection NVARCHAR(16),
    DeviceName NVARCHAR(16),
    CutTime DECIMAL(18,4),
    CutLength DECIMAL(18,4),
    Kerf DECIMAL(18,4),
    DevicePosition DECIMAL(18,4),
    Curvature NVARCHAR(38),
    AChipOnly SMALLINT,
    BChipOnly SMALLINT,
    ChipOnlySolution SMALLINT,
    AAxisPasses INT,
    NumberOfTurns INT,
    AChipReductionPasses INT,
    BChipReductionPasses INT,
    HasFreq INT,
    NaturalFreq NVARCHAR(38),
    Confidence INT,
    CurveDeflection NVARCHAR(38),
    PassCount INT,
    FlareCount INT,
    Ovality NVARCHAR(38),
    EdgerFlitchCount INT,
    SubWidthBoardCount INT,
    NumberOfCants INT,
    OptTimeClass NVARCHAR(50),
    CantBoardCount INT,
    CantFinishedVolume NVARCHAR(38),
    TurnDescription NVARCHAR(50),
    DetectedTurnError NVARCHAR(38),
    CorrectedTurnError NVARCHAR(38),
    UncorrectedTurnError NVARCHAR(38),
    ClassifiedDetectedTurnError NVARCHAR(50),
    ClassifiedCorrectedTurnError NVARCHAR(50),
    ClassifiedUncorrectedTurnError NVARCHAR(50),
    NumberOfA1Cuts INT,
    NumberOfA2Cuts INT,
    NumberOfB1Cuts INT,
    NumberOfB2Cuts INT,
    AcousticVelocity NVARCHAR(38),
    VelocityClass NVARCHAR(50),
    TagNames NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    VolumeType_1 NVARCHAR(50),
    VolumeUnits_1 NVARCHAR(50),
    VolumeType_2 NVARCHAR(50),
    VolumeUnits_2 NVARCHAR(50),
    VolumeType_3 NVARCHAR(50),
    VolumeUnits_3 NVARCHAR(255),
    IDLogView INT IDENTITY(1,1) PRIMARY KEY
);

CREATE TABLE fpusnr_shift_logdetail (
    LogId INT,
    MachineId INT,
    StemId INT,
    DateTime DATE,
    SpeciesName NVARCHAR(MAX),
    GradeName NVARCHAR(MAX),
    Sweep DECIMAL(18,4),
    Taper DECIMAL(18,4),
    Ovality DECIMAL(18,4),
    SmallEndDiameter DECIMAL(18,4),
    LargeEndDiameter DECIMAL(18,4),
    Shift INT,
    IsMetric INT,
    PieceCount INT,
    ProductionValue DECIMAL(18,4),
    MarketValue DECIMAL(18,4),
    UserVolume DECIMAL(18,4),
    AdjustedGrossVol DECIMAL(18,4),
    NominalLumberVolume DECIMAL(18,4),
    LogNumber DECIMAL(18,4),
    Length DECIMAL(18,4),
    DiameterDescription NVARCHAR(MAX),
    LengthDescription NVARCHAR(MAX),
    BinId INT,
    SolutionType NVARCHAR(MAX),
    FiberClass NVARCHAR(MAX),
    UserVolume_1 DECIMAL(18,4),
    OptTime DECIMAL(18,4),
    ForceTerm INT,
    IsSimulation INT,
    ChipVolume DECIMAL(18,4),
    ChipValue DECIMAL(18,4),
    SawdustVolume DECIMAL(18,4),
    SawdustValue DECIMAL(18,4),
    Confidence INT,
    Harmonic INT,
    CurveDeflection DECIMAL(18,4),
    EdgerFlitchCount INT,
    SubWidthBoardCount INT,
    Crew NVARCHAR(MAX),
    SweepClass NVARCHAR(MAX),
    OptTimeClass NVARCHAR(MAX),
    AcousticVelocity DECIMAL(18,4),
    VelocityClass NVARCHAR(MAX),
    RealDateTime DATE,
    fld_quart INT,
    fld_DateQuart DATE,
    fld_TempsCoupe DECIMAL(18,4),
    fld_TempsDowntime DECIMAL(18,4),
    IDUSNR INT
);

CREATE TABLE fpusnr_shift_logdetailArc (
    LogId INT,
    MachineId INT,
    StemId INT,
    DateTime DATE,
    SpeciesName NVARCHAR(MAX),
    GradeName NVARCHAR(MAX),
    Sweep DECIMAL(18,4),
    Taper DECIMAL(18,4),
    Ovality DECIMAL(18,4),
    SmallEndDiameter DECIMAL(18,4),
    LargeEndDiameter DECIMAL(18,4),
    Shift INT,
    IsMetric INT,
    PieceCount INT,
    ProductionValue DECIMAL(18,4),
    MarketValue DECIMAL(18,4),
    UserVolume DECIMAL(18,4),
    AdjustedGrossVol DECIMAL(18,4),
    NominalLumberVolume DECIMAL(18,4),
    LogNumber DECIMAL(18,4),
    Length DECIMAL(18,4),
    DiameterDescription NVARCHAR(MAX),
    LengthDescription NVARCHAR(MAX),
    BinId INT,
    SolutionType NVARCHAR(MAX),
    FiberClass NVARCHAR(MAX),
    UserVolume_1 DECIMAL(18,4),
    OptTime DECIMAL(18,4),
    ForceTerm INT,
    IsSimulation INT,
    ChipVolume DECIMAL(18,4),
    ChipValue DECIMAL(18,4),
    SawdustVolume DECIMAL(18,4),
    SawdustValue DECIMAL(18,4),
    Confidence INT,
    Harmonic INT,
    CurveDeflection DECIMAL(18,4),
    EdgerFlitchCount INT,
    SubWidthBoardCount INT,
    Crew NVARCHAR(MAX),
    SweepClass NVARCHAR(MAX),
    OptTimeClass NVARCHAR(MAX),
    AcousticVelocity DECIMAL(18,4),
    VelocityClass NVARCHAR(MAX),
    RealDateTime DATE,
    fld_quart INT,
    fld_DateQuart DATE,
    fld_TempsCoupe DECIMAL(18,4),
    fld_TempsDowntime DECIMAL(18,4),
    IDUSNR INT
);

CREATE TABLE fpusnr_DowntimeStatusConfig (
    Code NVARCHAR(50),
    Colour DECIMAL(18,4),
    Group NVARCHAR(50),
    Renamable NVARCHAR(MAX),
    Description NVARCHAR(50),
    Source NVARCHAR(50),
    PK_DowntimeStatusConfig NVARCHAR(MAX)
);

CREATE TABLE fpusnr_Arc_downtime_view (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Crew NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    EndTime DATETIME2,
    fld_NoDowntime INT
);

CREATE TABLE fpusnr_arc_downtime_view_autre (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagStartTime DATETIME2,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    fld_NoDowntime INT
);

CREATE TABLE fpusnr_downtime_view (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagStartTime DATETIME2,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    fld_NoDowntime INT IDENTITY(1,1) PRIMARY KEY,
    fld_Commentaire NVARCHAR(50),
    fld_PasUnArret INT,
    fld_DurationBase DECIMAL(18,4),
    fld_DateModif DATE,
    fld_ModifierPar NVARCHAR(30),
    _dta_index_fpusnr_downtime_vi NVARCHAR(MAX),
    StartTimeDownTimeCodeShiftno NVARCHAR(MAX),
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_TypePause INT,
    fld_dateModif NVARCHAR(MAX)
);

CREATE TABLE fpusnr_downtime_view_autre (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagStartTime DATETIME2,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    fld_NoDowntime INT IDENTITY(1,1) PRIMARY KEY
);

CREATE TABLE tbl_periode (
    fld_Annee INT,
    fld_Semaine INT,
    fld_dateDebut NVARCHAR(MAX),
    fld_dateFin NVARCHAR(MAX)
);

CREATE TABLE tbl_VerificationUsnr (
    IdVerification INT IDENTITY(1,1) PRIMARY KEY,
    fld_Date DATE,
    fld_Quart NVARCHAR(10),
    fld_EnvoiFinal SMALLINT,
    fld_Usager NVARCHAR(50),
    fld_DateFait DATE,
    fld_DateApprouver DATE,
    fld_ApprouverPar NVARCHAR(50),
    PK_tbl_VerificationUsnr NVARCHAR(MAX)
);

CREATE TABLE tbl_Connexion (
    IDtbl_Connexion INT IDENTITY(1,1) PRIMARY KEY,
    fld_NomConnexion NVARCHAR(50),
    fld_Serveur NVARCHAR(50),
    fld_MotPasse NVARCHAR(50),
    fld_BaseDeDonnee NVARCHAR(50)
);

CREATE TABLE fpusnr_downtime_view_traiter (
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_NoDowntime FLOAT,
    fld_Commentaire NVARCHAR(50),
    fld_TypePause INT,
    fld_PasUnArret INT,
    fld_dateModif NVARCHAR(MAX),
    fld_ModifierPar NVARCHAR(30)
);

CREATE TABLE tbl_Trace (
    fld_NoTrace INT IDENTITY(1,1) PRIMARY KEY,
    fld_Fenetre NVARCHAR(50),
    fld_Usager NVARCHAR(30),
    fld_StartTime NVARCHAR(50),
    fld_DateheureModifier DATE,
    fld_Commentaire NVARCHAR(50)
);

CREATE TABLE fpusnr_Courriel (
    fld_IdCourriel INT IDENTITY(1,1) PRIMARY KEY,
    fld_courriel NVARCHAR(70),
    fld_Directeur SMALLINT
);

CREATE TABLE fpusnr_arc_logimporter (
    fld_IDNo INT,
    fld_Date DATE,
    IDLogUSNR INT
);

CREATE TABLE fpusnr_logimporter (
    fld_IDNo INT IDENTITY(1,1) PRIMARY KEY,
    fld_Date DATE,
    IDLogUSNR INT,
    fld_DateIdLogUSNR DATE
);

CREATE TABLE fpusnr_arc_downtime_view_traiter (
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_NoDowntime FLOAT
);

CREATE TABLE fpusnr_downtime_enmarche_traiter (
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_NoDowntime FLOAT
);

CREATE TABLE fpusnr_downtimemessage (
    fld_IdDownTimeMessage INT IDENTITY(1,1) PRIMARY KEY,
    fld_DatedernierDowntime DATE,
    fld_Messageenvoyer SMALLINT
);

CREATE TABLE tbl_PasTempsArret (
    fld_IDPasUnArret INT IDENTITY(1,1) PRIMARY KEY,
    fld_DescPasUnArret NVARCHAR(50)
);

CREATE TABLE tbl_TempsPause (
    IDTypePause INT IDENTITY(1,1) PRIMARY KEY,
    fld_DescriptionPause NVARCHAR(25),
    fld_Duree INT
);

CREATE TABLE tbl_DowntimeSupprimer (
    fld_DowntimeDelete INT IDENTITY(1,1) PRIMARY KEY,
    fld_StartTime DATETIME2
);

CREATE TABLE tbl_Parametre (
    fld_IDParam DECIMAL(18,4),
    fld_PlusPetiteValeur DECIMAL(18,4),
    fld_EnleverDuRapport DECIMAL(18,4)
);

CREATE TABLE tbl_tableimporter (
    fld_IdImporter INT IDENTITY(1,1) PRIMARY KEY,
    fld_NomTable NVARCHAR(45)
);

CREATE TABLE tbl_tempsarret_machine (
    idTempsArretMachine INT IDENTITY(1,1) PRIMARY KEY,
    fld_Machine NVARCHAR(45),
    fld_TempsArret NVARCHAR(50),
    tbl_tempsarret_machine$Machin NVARCHAR(MAX)
);

CREATE TABLE fpusnr_shifttimes (
    ShiftId INT,
    MondayStart DATETIME2,
    MondayEnd DATETIME2,
    TuesdayStart DATETIME2,
    TuesdayEnd DATETIME2,
    WednesdayStart DATETIME2,
    WednesdayEnd DATETIME2,
    ThursdayStart DATETIME2,
    ThursdayEnd DATETIME2,
    FridayStart DATETIME2,
    FridayEnd DATETIME2,
    SaturdayStart DATETIME2,
    SaturdayEnd DATETIME2,
    SundayStart DATETIME2,
    SundayEnd DATETIME2,
    manualOverride SMALLINT,
    isCached SMALLINT
);

CREATE TABLE fpusnr_zlk_shift (
    ShiftNumber INT,
    ShiftName NVARCHAR(50),
    PLCShiftNumber INT
);

CREATE TABLE fpusnr_DowtimeImport (
    StartTime DATETIME2
);

CREATE TABLE fpusnr_arc_downtime_view_autr (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagStartTime DATETIME2,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    fld_NoDowntime INT
);

CREATE TABLE fpusnr_arc_downtime_view_trait (
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_NoDowntime FLOAT
);

CREATE TABLE fpusnr_downtime_enmarche_tra (
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_NoDowntime FLOAT
);

CREATE TABLE fpusnr_downtime_vi (
    Machine NVARCHAR(50),
    DowntimeCode NVARCHAR(50),
    Shift NVARCHAR(50),
    Duration DECIMAL(18,4),
    DateTime DATE,
    RecordCount INT,
    TagStartTime DATETIME2,
    TagNames NVARCHAR(MAX),
    TagValues NVARCHAR(MAX),
    TagDateTimeEnd DATE,
    GroupType NVARCHAR(50),
    StartTime DATETIME2,
    fld_NoDowntime INT IDENTITY(1,1) PRIMARY KEY,
    fld_Commentaire NVARCHAR(50),
    fld_PasUnArret INT,
    fld_DurationBase DECIMAL(18,4),
    fld_DateModif DATE,
    fld_ModifierPar NVARCHAR(30),
    _dta_index_fpusnr_downtime_vi NVARCHAR(MAX),
    StartTimeDownTimeCodeShiftno NVARCHAR(MAX),
    idtbl_perteTempstraite INT IDENTITY(1,1) PRIMARY KEY,
    fld_PT_IdPLC FLOAT,
    fld_PT_IdQuart FLOAT,
    fld_DateDebut DATE,
    fld_DateFin DATE,
    fld_Duree DECIMAL(18,4),
    fld_Equipement INT,
    fld_Description NVARCHAR(50),
    fld_DateRapportJour DATE,
    fld_QuartRapJour INT,
    fld_DateQuart DATE,
    fld_Quart INT,
    fld_TypePause INT,
    fld_dateModif NVARCHAR(MAX)
);

